name: .NET CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      
env:
 DOTNET_VERSION: '9.0.x'
 BUILD_CONFIGURATION: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Main branch message
        if: github.ref == 'refs/heads/main'
        run: echo "This is the main branch"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        # run: dotnet build --no-restore --configuration Release
        run: dotnet build --configuration $BUILD_CONFIGURATION

      - name: Publish application
        run: dotnet publish -c Release -o ./publish

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-build
          path: ./publish
        #   path: |
        #     **/bin/Release/**
        #     !**/bin/Release/**/ref/**

  test:
    needs: build
    runs-on: ubuntu-latest

    strategy:
     matrix:
        dotnet-version:
          - '9.0.x'

    steps:
     - name: Checkout source code
       uses: actions/checkout@v4

     - name: Setup .NET
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: ${{matrix.dotnet-version}}

     - name: Restore dependencies
       run: dotnet restore

    #  - name: Run tests
    #    run: dotnet test --configuration Release --logger "trx;LogFileName=test-results.trx"

     - name: Run tests
       run: dotnet test --configuration Release --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage"    

     - name: Publish test results
       if: always()
       uses: dorny/test-reporter@v2
       with:
        name: .NET Tests
        path: '**/TestResults/*.trx'
        reporter: dotnet-trx

     - name: Upload test results
       if: always()
       uses: actions/upload-artifact@v4
       with:
        name: test-results-${{ matrix.dotnet-version }}
        path: '**/TestResults/*.trx'

     - name: Upload code coverage
       if: always()
       uses: actions/upload-artifact@v4
       with:
            name: code-coverage-${{ matrix.dotnet-version }}
            path: '**/TestResults/**/coverage.cobertura.xml'